/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./cricket_stadium.glb
Author: aashraymukhi22 (https://sketchfab.com/aashraymukhi22)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cricket-stadium-b9e02471014e407eb3a3ad18a24b29b4
Title: Cricket Stadium
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cricket_stadium.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.31}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.None} />
      </group>
    </group>
  )
}

useGLTF.preload('/cricket_stadium.glb')
