/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/stadium_final.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.13, 7.55, 0.23]} scale={[5.76, 5.68, 5.76]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.016']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.014']} />
          </group>
          <group position={[-0.23, 7.98, -6.18]} scale={[0.36, 0.36, 0.65]}>
            <mesh geometry={nodes.Object_25.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Object_26.geometry} material={materials['Material.019']} />
          </group>
          <group position={[-0.23, 7.87, 6.74]} rotation={[-Math.PI, 0, 0]} scale={[0.36, 0.36, 0.65]}>
            <mesh geometry={nodes.Object_28.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Object_29.geometry} material={materials['Material.019']} />
          </group>
          <group position={[6.23, 7.98, 0.28]} rotation={[0, -1.57, 0]} scale={[0.36, 0.36, 0.65]}>
            <mesh geometry={nodes.Object_31.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Object_32.geometry} material={materials['Material.019']} />
          </group>
          <group position={[-6.69, 7.87, 0.28]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[0.36, 0.36, 0.65]}>
            <mesh geometry={nodes.Object_34.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Object_35.geometry} material={materials['Material.019']} />
          </group>
          <group position={[5.36, 9.18, 5.31]} rotation={[-Math.PI, -0.84, 0]} scale={[0.43, 0.6, 0.57]}>
            <mesh geometry={nodes.Object_40.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Object_41.geometry} material={materials['Material.019']} />
          </group>
          <group position={[4.77, 9.18, -5.34]} rotation={[0, -0.73, Math.PI]} scale={[0.43, 0.6, 0.57]}>
            <mesh geometry={nodes.Object_43.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Object_44.geometry} material={materials['Material.019']} />
          </group>
          <group position={[-5.3, 9.18, 5.91]} rotation={[-Math.PI, 0.73, 0]} scale={[0.43, 0.6, 0.57]}>
            <mesh geometry={nodes.Object_46.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Object_47.geometry} material={materials['Material.019']} />
          </group>
          <group position={[-5.89, 9.18, -4.75]} rotation={[0, 0.84, -Math.PI]} scale={[0.43, 0.6, 0.57]}>
            <mesh geometry={nodes.Object_37.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Object_38.geometry} material={materials['Material.019']} />
          </group>
          <group position={[-0.25, 13.15, 10.31]} rotation={[-1.68, 0, 0]} scale={[-0.64, -0.07, -0.39]}>
            <mesh geometry={nodes.Object_77.geometry} material={materials['Material.030']} />
            <mesh geometry={nodes.Object_78.geometry} material={materials['Material.031']} />
          </group>
          <group position={[-10.12, 13.15, 0.44]} rotation={[-Math.PI / 2, 0.11, -Math.PI / 2]} scale={[-0.64, -0.07, -0.39]}>
            <mesh geometry={nodes.Object_80.geometry} material={materials['Material.030']} />
            <mesh geometry={nodes.Object_81.geometry} material={materials['Material.031']} />
          </group>
          <group position={[9.61, 13.15, 0.44]} rotation={[-Math.PI / 2, -0.11, Math.PI / 2]} scale={[-0.64, -0.07, -0.39]}>
            <mesh geometry={nodes.Object_83.geometry} material={materials['Material.030']} />
            <mesh geometry={nodes.Object_84.geometry} material={materials['Material.031']} />
          </group>
          <group position={[-0.25, 13.15, -9.42]} rotation={[-1.46, 0, -Math.PI]} scale={[-0.64, -0.07, -0.39]}>
            <mesh geometry={nodes.Object_74.geometry} material={materials['Material.030']} />
            <mesh geometry={nodes.Object_75.geometry} material={materials['Material.031']} />
          </group>
          <group position={[-1.04, 6.51, -13.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_86.geometry} material={materials.material_0} />
          </group>
          <group position={[-4.67, 6.51, -13.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_88.geometry} material={materials.material_0} />
          </group>
          <group position={[-8.39, 6.51, -13.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_90.geometry} material={materials.material_0} />
          </group>
          <group position={[9.83, 6.51, -13.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_92.geometry} material={materials.material_0} />
          </group>
          <group position={[6.49, 6.51, -13.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_94.geometry} material={materials.material_0} />
          </group>
          <group position={[2.8, 6.51, -13.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_96.geometry} material={materials.material_0} />
          </group>
          <group position={[-12.98, 6.51, -13.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_98.geometry} material={materials.material_0} />
          </group>
          <group position={[-13.83, 6.51, -12.86]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_100.geometry} material={materials.material_0} />
          </group>
          <group position={[-13.81, 6.51, 1.2]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_102.geometry} material={materials.material_0} />
          </group>
          <group position={[-13.81, 6.51, 4.83]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_104.geometry} material={materials.material_0} />
          </group>
          <group position={[-13.81, 6.51, 8.56]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_106.geometry} material={materials.material_0} />
          </group>
          <group position={[-13.81, 6.51, -9.67]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_108.geometry} material={materials.material_0} />
          </group>
          <group position={[-13.81, 6.51, -6.33]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_110.geometry} material={materials.material_0} />
          </group>
          <group position={[-13.81, 6.51, -2.64]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_112.geometry} material={materials.material_0} />
          </group>
          <group position={[-13.81, 6.51, 13.14]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_114.geometry} material={materials.material_0} />
          </group>
          <group position={[-13.12, 6.51, 13.99]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_116.geometry} material={materials.material_0} />
          </group>
          <group position={[0.9, 6.51, 13.98]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_118.geometry} material={materials.material_0} />
          </group>
          <group position={[4.53, 6.51, 13.98]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_120.geometry} material={materials.material_0} />
          </group>
          <group position={[8.26, 6.51, 13.98]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_122.geometry} material={materials.material_0} />
          </group>
          <group position={[-9.97, 6.51, 13.98]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_124.geometry} material={materials.material_0} />
          </group>
          <group position={[-6.63, 6.51, 13.98]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_126.geometry} material={materials.material_0} />
          </group>
          <group position={[-2.94, 6.51, 13.98]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_128.geometry} material={materials.material_0} />
          </group>
          <group position={[12.84, 6.51, 13.98]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_130.geometry} material={materials.material_0} />
          </group>
          <group position={[13.69, 6.51, 13.29]} rotation={[0, 1.57, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_132.geometry} material={materials.material_0} />
          </group>
          <group position={[13.71, 6.51, -0.61]} rotation={[0, 1.57, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_134.geometry} material={materials.material_0} />
          </group>
          <group position={[13.71, 6.51, -4.24]} rotation={[0, 1.57, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_136.geometry} material={materials.material_0} />
          </group>
          <group position={[13.71, 6.51, -7.96]} rotation={[0, 1.57, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_138.geometry} material={materials.material_0} />
          </group>
          <group position={[13.71, 6.51, 10.26]} rotation={[0, 1.57, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_140.geometry} material={materials.material_0} />
          </group>
          <group position={[13.71, 6.51, 6.92]} rotation={[0, 1.57, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_142.geometry} material={materials.material_0} />
          </group>
          <group position={[13.71, 6.51, 3.23]} rotation={[0, 1.57, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_144.geometry} material={materials.material_0} />
          </group>
          <group position={[13.71, 6.51, -12.55]} rotation={[0, 1.57, 0]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_146.geometry} material={materials.material_0} />
          </group>
          <group position={[13.02, 6.51, -13.39]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.78, -0.04, -0.1]}>
            <mesh geometry={nodes.Object_148.geometry} material={materials.material_0} />
          </group>
          <group position={[-0.13, 7.55, 0.23]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.5, -0.01, -0.24]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
          </group>
          <group position={[1.16, 7.74, 0.17]} scale={[0.02, 0.18, 0.02]}>
            <mesh geometry={nodes.Object_17.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_18.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Object_19.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Object_20.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_21.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Object_22.geometry} material={materials['Material.011']} />
            <mesh geometry={nodes.Object_23.geometry} material={materials['Material.010']} />
          </group>
          <group position={[-1.5, 7.74, 0.17]} scale={[0.02, 0.18, 0.02]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.011']} />
            <mesh geometry={nodes.Object_15.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-0.23, 7.59, 0.35]} scale={[6.59, 0.21, 6.59]}>
            <mesh geometry={nodes.Object_51.geometry} material={materials['Material.017']} />
          </group>
          <group position={[-0.23, 7.59, 0.35]} scale={[6.97, 0.21, 6.97]}>
            <mesh geometry={nodes.Object_53.geometry} material={materials['Material.017']} />
          </group>
          <group position={[-0.23, 7.61, 0.35]} scale={[7.28, 0.21, 7.28]}>
            <mesh geometry={nodes.Object_55.geometry} material={materials['Material.017']} />
          </group>
          <group position={[-0.23, 8.47, 0.35]} scale={[7.04, 0.06, 7.04]}>
            <mesh geometry={nodes.Object_68.geometry} material={materials['Material.020']} />
          </group>
          <group position={[-0.23, 6.72, 0.3]} scale={[7.83, 0.16, 7.83]}>
            <mesh geometry={nodes.Object_66.geometry} material={materials['Material.022']} />
          </group>
          <group position={[-0.23, 6.72, 0.3]} scale={[8.22, 0.16, 8.22]}>
            <mesh geometry={nodes.Object_57.geometry} material={materials['Material.022']} />
          </group>
          <group position={[-0.23, 6.72, 0.3]} scale={[8.61, 0.16, 8.61]}>
            <mesh geometry={nodes.Object_59.geometry} material={materials['Material.022']} />
            <mesh geometry={nodes.Object_60.geometry} material={materials['Material.026']} />
            <mesh geometry={nodes.Object_61.geometry} material={materials['Material.027']} />
            <mesh geometry={nodes.Object_62.geometry} material={materials['Material.028']} />
            <mesh geometry={nodes.Object_63.geometry} material={materials['Material.029']} />
            <mesh geometry={nodes.Object_64.geometry} material={materials['Material.013']} />
          </group>
          <group position={[-0.23, 6.72, 0.3]} scale={[8.68, 0.16, 8.68]}>
            <mesh geometry={nodes.Object_70.geometry} material={materials['Material.023']} />
            <mesh geometry={nodes.Object_71.geometry} material={materials['Material.024']} />
            <mesh geometry={nodes.Object_72.geometry} material={materials['Material.025']} />
          </group>
          <group position={[-2.49, 8.81, -2.71]} rotation={[-Math.PI, 1.28, -Math.PI]} scale={[4.36, 0.07, 4.38]}>
            <mesh geometry={nodes.Object_153.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_154.geometry} material={materials['Material.006']} />
          </group>
          <group position={[-0.23, 7.59, 0.35]} scale={[6.3, 0.2, 6.3]}>
            <mesh geometry={nodes.Object_49.geometry} material={materials['Material.017']} />
          </group>
          <group position={[7.59, 8.07, 9.68]} rotation={[0, 1.57, 0]} scale={-0.27}>
            <mesh geometry={nodes.Object_156.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_157.geometry} material={materials['Material.035']} />
          </group>
          <group position={[-5.69, 8.07, 10.38]} rotation={[0, -0.48, 0]} scale={-0.27}>
            <mesh geometry={nodes.Object_159.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_160.geometry} material={materials['Material.035']} />
          </group>
          <group position={[-8.61, 8.07, 6.09]} rotation={[0, 1.56, 0]} scale={-0.27}>
            <mesh geometry={nodes.Object_162.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_163.geometry} material={materials['Material.035']} />
          </group>
          <group position={[3.18, 8.07, 11.57]} rotation={[0, 1.56, 0]} scale={-0.27}>
            <mesh geometry={nodes.Object_165.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_166.geometry} material={materials['Material.035']} />
          </group>
          <group position={[-8.46, 8.07, -8.35]} rotation={[0, 1.56, 0]} scale={-0.27}>
            <mesh geometry={nodes.Object_168.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_169.geometry} material={materials['Material.035']} />
          </group>
          <group position={[-10.97, 8.07, 1.27]} rotation={[Math.PI, -0.03, Math.PI]} scale={-0.27}>
            <mesh geometry={nodes.Object_171.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_172.geometry} material={materials['Material.035']} />
          </group>
          <group position={[8.6, 8.07, -8.17]} rotation={[0, -1.45, 0]} scale={-0.27}>
            <mesh geometry={nodes.Object_174.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_175.geometry} material={materials['Material.035']} />
          </group>
          <group position={[-2.39, 8.07, -10.67]} rotation={[0, -1.13, 0]} scale={-0.27}>
            <mesh geometry={nodes.Object_177.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_178.geometry} material={materials['Material.035']} />
          </group>
          <group position={[9.81, 8.07, 2.02]} rotation={[0, 1.57, 0]} scale={-0.27}>
            <mesh geometry={nodes.Object_180.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_181.geometry} material={materials['Material.035']} />
          </group>
          <group position={[10.67, 8.07, -4]} rotation={[-Math.PI, 0.28, -Math.PI]} scale={-0.27}>
            <mesh geometry={nodes.Object_183.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.Object_184.geometry} material={materials['Material.035']} />
          </group>
          <group position={[-0.23, 6.47, 0.35]} scale={[15.72, 13.99, 15.72]}>
            <mesh geometry={nodes.Object_150.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_151.geometry} material={materials['Material.003']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/stadium_final.glb')
